<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use App\Models\PropertyCategory;
use App\Models\Location;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        // Define standard property categories
        $categoriesList = ['Villa', 'House', 'Land', 'Hotel', 'Restaurant', 'Rent'];
        $categories = [];
        foreach ($categoriesList as $catName) {
            $categories[$catName] = PropertyCategory::firstOrCreate(
                ['slug' => Str::slug($catName)],
                [
                    'name' => $catName,
                    'icon' => in_array($catName, ['Villa', 'Rent']) ? 'home' : ($catName === 'House' ? 'building' : ($catName === 'Land' ? 'map-pin' : ($catName === 'Hotel' ? 'briefcase' : 'coffee'))),
                    'status' => 'active',
                ]
            );
        }

        // Fetch existing locations (23 verified North Bali locations)
        $locations = Location::all()->keyBy('name');

        // Authentic listings audited from old PT Lovina North Bali Real Estate Agency website
        $authenticListings = [
    [
        'name' => '3 bedrooms House in Tukadmungga',
        'location' => 'Tukad Mungga',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => '10 are Land in Kayuputih Good Access',
        'location' => 'Kayu Putih',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Beautiful Property in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => '35 are Flat land Kaliasem with Beautiful Ricefield & Mountain View',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '40 are beautiful Oceanview Land Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '25 and 5 are Land Kayu Putih',
        'location' => 'Kayu Putih',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '18 Are Land with Beautiful View in Tanguwisia',
        'location' => 'Tangguwisia',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '18.2 Are Land Kaliasem Close to Central',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Great Location Resort in Lovina',
        'location' => 'Lovina',
        'category' => 'Hotel',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => 'Good Investment Opportunity with Great View',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '2 Bedroom House in Banyualit Close to Toko Rejeki',
        'location' => 'Banyualit',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '35 Are Land Close to The Beach in Dencarik',
        'location' => 'Dencarik',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '10 Are Land Close to The Beach In Dencarik',
        'location' => 'Dencarik',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Premium Land Close to The Beach',
        'location' => 'Dencarik',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Nice Villa in Lovina',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '1.5 Are & 3.5 Are Land Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '4 Are Land Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '3 Are House Banyualit',
        'location' => 'Banyualit',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Brand-New Villa for Sale in Lovina',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => 'Unique Villa with Rice Field Views Central Lovina',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '3 Bedroom Villa with Superb View Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '2 Bedroom Brand-new House in Kaliasem with Good Access',
        'location' => 'Kaliasem',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '15 Are Land in Kayuputih',
        'location' => 'Kayu Putih',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Superb Villa on The Beach',
        'location' => 'Temukus',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => 'Villa with Pool in Kayuputih',
        'location' => 'Kayu Putih',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '2 Bedroom Villa with Pool Close to The Central',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '20 Are Flat Land in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '25 Are Land with View in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '2 Bedroom House for Rent Kalibukbuk',
        'location' => 'Kalibukbuk',
        'category' => 'Rent',
        'ownership_type' => 'Leasehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'New Villa in Celuk Buluh',
        'location' => 'Celuk Buluh',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Villa with Ocean and Sunset View',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Villa with Pool in Kalibukbuk',
        'location' => 'Kalibukbuk',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'House in Sanggalangit',
        'location' => 'Sanggalangit',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Villa Right on The Beach',
        'location' => 'Temukus',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Beachfront Villa in Dencarik',
        'location' => 'Dencarik',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Business Opportunity in Sambangan',
        'location' => 'Sambangan',
        'category' => 'Hotel',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Big Villa, Fantastic Views, A Must See',
        'location' => 'Kayu Putih',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Cozy Place in Kalibukbuk',
        'location' => 'Kalibukbuk',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '2.3 Hectare Land in Cempaga Hills',
        'location' => 'Cempaga',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Newly Renovated Villa 50 Meters from The Beach Central Lovina',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => 'High Quality Build House in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '98 Are Dividable Land with Superb Ocean View in Kayu Putih',
        'location' => 'Kayu Putih',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '7.5 Are Land In Anturan',
        'location' => 'Anturan',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Brand New 2 Storey Villa in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Newly Built Villa Celukbuluh',
        'location' => 'Celuk Buluh',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Well Maintained Villa in Kalibukbuk',
        'location' => 'Kalibukbuk',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '89 are land in Tukad Mungga',
        'location' => 'Tukad Mungga',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '30 are Land with Mountain and Ocean View in Sambangan Near Aling Aling',
        'location' => 'Sambangan',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Absolute beachfront Villa in Temukus',
        'location' => 'Temukus',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => '25 Are Land with Nice View in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '25 Are Great Ocean View Land in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '50 Are Land in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Traditional House in The Village',
        'location' => 'Banjar',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Teak Joglo House with Stunning View',
        'location' => 'Banjar',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'REDUCED IN PRICE: 2.3 are Beautiful Villa in Celukbuluh',
        'location' => 'Celuk Buluh',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '6.8 are Local House in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '40 Are Land with Beton Road and Ocean View in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Unique Shaped Villa in Banjar',
        'location' => 'Banjar',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '24 are Land in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '50 are Land with Beautiful Ocean View in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '42 Are Land in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '9.5 are Land in Kaliasem',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '20 Are flat land in Anturan',
        'location' => 'Anturan',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '8 Are Land in Anturan',
        'location' => 'Anturan',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '10 Are Land in Anturan',
        'location' => 'Anturan',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '6.7 Are land in Banyualit with optional 3 are land',
        'location' => 'Banyualit',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '5 Are Land in Kaliasem with Good Access',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '6 Are Land in Kaliasem with good access',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '7 Are land in Kaliasem with good access',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '6 Are Land in Kaliasem with Good Access',
        'location' => 'Kaliasem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Beautiful Land in Gambuh with Nice View',
        'location' => 'Gambuh',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '7.5, 12 are Land with Houses and 37.5 are Land in Selat',
        'location' => 'Selat',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => '4 Bedroom Villa in Central Lovina',
        'location' => 'Lovina',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => true,
    ],
    [
        'name' => '3 bedroom House Tegal linggah',
        'location' => 'Tegal Linggah',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Beachfront Land in Kubutambahan',
        'location' => 'Kubutambahan',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Villa in Sing-Sing',
        'location' => 'Sing-Sing',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Land Plot in Sulanyah',
        'location' => 'Sulanyah',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Seaside Land in Bondalem',
        'location' => 'Bondalem',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Coastal Land in Gerokgak',
        'location' => 'Gerokgak',
        'category' => 'Land',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Ocean View Villa in Gerokgak',
        'location' => 'Gerokgak',
        'category' => 'Villa',
        'ownership_type' => 'Freehold',
        'status' => 'published',
        'is_featured' => false,
    ],
    [
        'name' => 'Sunset Ridge House Draft',
        'location' => 'Lovina',
        'category' => 'House',
        'ownership_type' => 'Freehold',
        'status' => 'draft',
        'is_featured' => false,
    ],
];

        $usedSlugs = [];

        foreach ($authenticListings as $index => $item) {
            $loc = $locations->get($item['location']);
            $cat = $categories[$item['category']] ?? null;

            if (!$loc || !$cat) {
                continue;
            }

            $baseSlug = Str::slug($item['name']);
            if (empty($baseSlug)) {
                $baseSlug = 'property-' . ($index + 1);
            }
            $slug = $baseSlug;
            $suffix = 1;
            while (in_array($slug, $usedSlugs) || Property::where('slug', $slug)->where('name', '!=', $item['name'])->exists()) {
                $suffix++;
                $slug = $baseSlug . '-' . $suffix;
            }
            $usedSlugs[] = $slug;

            Property::updateOrCreate(
                ['name' => $item['name']],
                [
                    'slug' => $slug,
                    'category_id' => $cat->id,
                    'location_id' => $loc->id,
                    'price' => null,
                    'ownership_type' => $item['ownership_type'],
                    'status' => $item['status'],
                    'is_featured' => $item['is_featured'],
                    'description' => null,
                    'short_description' => null,
                    'bedrooms' => null,
                    'bathrooms' => null,
                    'land_size' => null,
                    'building_size' => null,
                    'garage' => null,
                    'swimming_pool' => false,
                    'features' => null,
                    'electricity' => null,
                    'water_supply' => null,
                    'furnishing' => null,
                    'air_conditioning' => null,
                ]
            );
        }
    }
}
