<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Property;
use App\Models\PropertyCategory;
use App\Models\Location;
use Illuminate\Support\Str;

class PropertySeeder extends Seeder
{
    public function run(): void
    {
        // Define categories
        $categoriesList = ['Villa', 'House', 'Land', 'Hotel', 'Restaurant', 'Rent'];
        $categories = [];
        foreach ($categoriesList as $catName) {
            $categories[$catName] = PropertyCategory::firstOrCreate(
                ['slug' => Str::slug($catName)],
                [
                    'name' => $catName,
                    'icon' => $catName === 'Villa' || $catName === 'Rent' ? 'home' : ($catName === 'House' ? 'building' : ($catName === 'Land' ? 'map-pin' : ($catName === 'Hotel' ? 'briefcase' : 'coffee'))),
                    'status' => 'active',
                ]
            );
        }

        // Define locations
        $locationsList = ['Lovina', 'Temukus', 'Singaraja', 'Sererit', 'Banjar', 'Gerokgak'];
        $locations = [];
        foreach ($locationsList as $locName) {
            $locations[$locName] = Location::firstOrCreate(
                ['slug' => Str::slug($locName)],
                [
                    'name' => $locName,
                    'description' => "Beautiful location in {$locName}, North Bali.",
                    'image' => 'locations/' . Str::slug($locName) . '.jpg',
                    'is_popular' => in_array($locName, ['Lovina', 'Temukus', 'Banjar']),
                    'status' => 'active',
                ]
            );
        }

        // List of 48 properties to seed (distributed evenly across 6 categories and 6 locations)
        $properties = [
            // Category: Villa
            [
                'name' => 'Sunset Bay Villa',
                'category' => 'Villa',
                'location' => 'Lovina',
                'price' => 450000,
                'ownership_type' => 'Freehold',
                'is_featured' => true,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'land_size' => 720,
                'building_size' => 380,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Harmony Pool Retreat',
                'category' => 'Villa',
                'location' => 'Banjar',
                'price' => 320000,
                'ownership_type' => 'Freehold',
                'is_featured' => true,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'land_size' => 600,
                'building_size' => 320,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Ocean Breeze Estate',
                'category' => 'Villa',
                'location' => 'Temukus',
                'price' => 580000,
                'ownership_type' => 'Freehold',
                'is_featured' => true,
                'bedrooms' => 5,
                'bathrooms' => 4,
                'land_size' => 850,
                'building_size' => 420,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Tropical Bay Villa',
                'category' => 'Villa',
                'location' => 'Sererit',
                'price' => 210000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => 400,
                'building_size' => 200,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Serenity Hill Villa',
                'category' => 'Villa',
                'location' => 'Singaraja',
                'price' => 390000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'land_size' => 550,
                'building_size' => 310,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Gerokgak Cove Villa',
                'category' => 'Villa',
                'location' => 'Gerokgak',
                'price' => 295000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'land_size' => 500,
                'building_size' => 220,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Lovina Heights Sanctuary',
                'category' => 'Villa',
                'location' => 'Lovina',
                'price' => 480000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 4,
                'bathrooms' => 4,
                'land_size' => 800,
                'building_size' => 350,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Banjar Hot Springs Lodge',
                'category' => 'Villa',
                'location' => 'Banjar',
                'price' => 310000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => 580,
                'building_size' => 260,
                'swimming_pool' => true,
            ],

            // Category: House
            [
                'name' => 'Singaraja Family Home',
                'category' => 'House',
                'location' => 'Singaraja',
                'price' => 125000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => 200,
                'building_size' => 150,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Gerokgak Valley House',
                'category' => 'House',
                'location' => 'Gerokgak',
                'price' => 95000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'land_size' => 180,
                'building_size' => 100,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Lovina Suburban Townhouse',
                'category' => 'House',
                'location' => 'Lovina',
                'price' => 175000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => 220,
                'building_size' => 160,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Banjar Cozy Cottage',
                'category' => 'House',
                'location' => 'Banjar',
                'price' => 88000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'land_size' => 150,
                'building_size' => 90,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Temukus Modern House',
                'category' => 'House',
                'location' => 'Temukus',
                'price' => 145000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => 210,
                'building_size' => 140,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Sererit Green Villa House',
                'category' => 'House',
                'location' => 'Sererit',
                'price' => 115000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => 250,
                'building_size' => 130,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Singaraja Downtown Residence',
                'category' => 'House',
                'location' => 'Singaraja',
                'price' => 185000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 4,
                'bathrooms' => 3,
                'land_size' => 300,
                'building_size' => 220,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Gerokgak Mountain View Cottage',
                'category' => 'House',
                'location' => 'Gerokgak',
                'price' => 110000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'land_size' => 240,
                'building_size' => 110,
                'swimming_pool' => false,
            ],

            // Category: Land
            [
                'name' => 'Lovina Beachfront Land Plot',
                'category' => 'Land',
                'location' => 'Lovina',
                'price' => 250000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 1500,
                'building_size' => 0,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Temukus Cliffside Plot',
                'category' => 'Land',
                'location' => 'Temukus',
                'price' => 180000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 1000,
                'building_size' => 0,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Singaraja Investment Land',
                'category' => 'Land',
                'location' => 'Singaraja',
                'price' => 75000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 800,
                'building_size' => 0,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Sererit Fertile Land',
                'category' => 'Land',
                'location' => 'Sererit',
                'price' => 60000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 1200,
                'building_size' => 0,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Banjar Hilltop Plot',
                'category' => 'Land',
                'location' => 'Banjar',
                'price' => 90000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 900,
                'building_size' => 0,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Gerokgak Coastal Land',
                'category' => 'Land',
                'location' => 'Gerokgak',
                'price' => 130000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 2000,
                'building_size' => 0,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Lovina Commercial Plot',
                'category' => 'Land',
                'location' => 'Lovina',
                'price' => 320000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 1800,
                'building_size' => 0,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Temukus Beach Plot',
                'category' => 'Land',
                'location' => 'Temukus',
                'price' => 210000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 0,
                'land_size' => 1100,
                'building_size' => 0,
                'swimming_pool' => false,
            ],

            // Category: Hotel
            [
                'name' => 'Lovina Dolphin Boutique Hotel',
                'category' => 'Hotel',
                'location' => 'Lovina',
                'price' => 950000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 12,
                'bathrooms' => 14,
                'land_size' => 1500,
                'building_size' => 800,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Temukus Seaside Resort',
                'category' => 'Hotel',
                'location' => 'Temukus',
                'price' => 1200000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 18,
                'bathrooms' => 20,
                'land_size' => 2500,
                'building_size' => 1200,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Singaraja City Plaza Hotel',
                'category' => 'Hotel',
                'location' => 'Singaraja',
                'price' => 850000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 25,
                'bathrooms' => 25,
                'land_size' => 1200,
                'building_size' => 1500,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Sererit Eco Lodge',
                'category' => 'Hotel',
                'location' => 'Sererit',
                'price' => 450000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 8,
                'bathrooms' => 9,
                'land_size' => 2000,
                'building_size' => 500,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Banjar Hot Springs Resort',
                'category' => 'Hotel',
                'location' => 'Banjar',
                'price' => 650000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 10,
                'bathrooms' => 12,
                'land_size' => 1800,
                'building_size' => 750,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Gerokgak Nature Eco Hotel',
                'category' => 'Hotel',
                'location' => 'Gerokgak',
                'price' => 580000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 7,
                'bathrooms' => 8,
                'land_size' => 3000,
                'building_size' => 450,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Lovina Sands Resort',
                'category' => 'Hotel',
                'location' => 'Lovina',
                'price' => 1400000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 20,
                'bathrooms' => 22,
                'land_size' => 2800,
                'building_size' => 1600,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Sererit Beachfront Hotel',
                'category' => 'Hotel',
                'location' => 'Sererit',
                'price' => 980000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 14,
                'bathrooms' => 15,
                'land_size' => 1600,
                'building_size' => 900,
                'swimming_pool' => true,
            ],

            // Category: Restaurant
            [
                'name' => 'Lovina Seafood Bistro',
                'category' => 'Restaurant',
                'location' => 'Lovina',
                'price' => 220000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'land_size' => 350,
                'building_size' => 200,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Temukus Sunset Cafe',
                'category' => 'Restaurant',
                'location' => 'Temukus',
                'price' => 145000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 1,
                'land_size' => 200,
                'building_size' => 120,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Singaraja Culinary Hub',
                'category' => 'Restaurant',
                'location' => 'Singaraja',
                'price' => 350000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 4,
                'land_size' => 600,
                'building_size' => 450,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Sererit Garden Cafe',
                'category' => 'Restaurant',
                'location' => 'Sererit',
                'price' => 125000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'land_size' => 400,
                'building_size' => 150,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Banjar Riverview Eatery',
                'category' => 'Restaurant',
                'location' => 'Banjar',
                'price' => 165000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'land_size' => 300,
                'building_size' => 180,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Gerokgak Marina Restaurant',
                'category' => 'Restaurant',
                'location' => 'Gerokgak',
                'price' => 280000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 3,
                'land_size' => 500,
                'building_size' => 300,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Lovina Organic Kitchen',
                'category' => 'Restaurant',
                'location' => 'Lovina',
                'price' => 195000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'land_size' => 280,
                'building_size' => 160,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Singaraja Heritage Cafe',
                'category' => 'Restaurant',
                'location' => 'Singaraja',
                'price' => 170000,
                'ownership_type' => 'Freehold',
                'is_featured' => false,
                'bedrooms' => 0,
                'bathrooms' => 2,
                'land_size' => 250,
                'building_size' => 150,
                'swimming_pool' => false,
            ],

            // Category: Rent
            [
                'name' => 'Lovina Beachfront Apartment',
                'category' => 'Rent',
                'location' => 'Lovina',
                'price' => 1500,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'land_size' => 120,
                'building_size' => 120,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Hilltop View Studio',
                'category' => 'Rent',
                'location' => 'Banjar',
                'price' => 800,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'land_size' => 60,
                'building_size' => 60,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Cozy Town House',
                'category' => 'Rent',
                'location' => 'Singaraja',
                'price' => 1200,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 2,
                'land_size' => 150,
                'building_size' => 130,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Modern Rental Villa',
                'category' => 'Rent',
                'location' => 'Lovina',
                'price' => 2500,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 3,
                'bathrooms' => 3,
                'land_size' => 250,
                'building_size' => 200,
                'swimming_pool' => true,
            ],
            [
                'name' => 'Temukus Studio Loft',
                'category' => 'Rent',
                'location' => 'Temukus',
                'price' => 950,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'land_size' => 70,
                'building_size' => 70,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Sererit Cozy Apartment',
                'category' => 'Rent',
                'location' => 'Sererit',
                'price' => 750,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 2,
                'bathrooms' => 1,
                'land_size' => 90,
                'building_size' => 80,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Gerokgak Beach Bungalow',
                'category' => 'Rent',
                'location' => 'Gerokgak',
                'price' => 1100,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 2,
                'bathrooms' => 2,
                'land_size' => 180,
                'building_size' => 100,
                'swimming_pool' => false,
            ],
            [
                'name' => 'Banjar Mountain Studio',
                'category' => 'Rent',
                'location' => 'Banjar',
                'price' => 700,
                'ownership_type' => 'Leasehold',
                'is_featured' => false,
                'bedrooms' => 1,
                'bathrooms' => 1,
                'land_size' => 50,
                'building_size' => 50,
                'swimming_pool' => false,
            ],
        ];

        foreach ($properties as $propData) {
            $cat = $categories[$propData['category']];
            $loc = $locations[$propData['location']];

            Property::updateOrCreate(
                ['slug' => Str::slug($propData['name'])],
                [
                    'name' => $propData['name'],
                    'category_id' => $cat->id,
                    'location_id' => $loc->id,
                    'price' => $propData['price'] * 15000,
                    'ownership_type' => $propData['ownership_type'],
                    'status' => 'published',
                    'is_featured' => $propData['is_featured'],
                    'description' => "Luxury {$propData['category']} in {$propData['location']} featuring high-quality builds and premium amenities.",
                    'bedrooms' => $propData['bedrooms'],
                    'bathrooms' => $propData['bathrooms'],
                    'land_size' => $propData['land_size'],
                    'building_size' => $propData['building_size'],
                    'swimming_pool' => $propData['swimming_pool'],
                    'electricity' => '5500 VA',
                    'water_supply' => 'PDAM',
                    'views_count' => rand(50, 400),
                ]
            );
        }
    }
}
